# Generated by Django 4.2.6 on 2023-10-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suplimente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamente',
            name='cantitate',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
